<?php

namespace Database\Seeders;

use App\Models\Device;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class DeviceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Seeds realistic devices across various cities and countries.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $devices = [
            // 1. Tirunelveli - Samsung S24
            [
                'installation_id'            => 'INS-8F29A1',
                'firebase_installation_id'   => 'c7F9a1b2c3d4e5f6K2mP',
                'hardware_id'                => 'AND-S24-998877665544',
                'fcm_token'                  => 'fcm_token_samsung_s24_live_a8f29a1_gpscam_sample',
                'device_manufacturer'        => 'Samsung',
                'device_brand'               => 'Samsung',
                'device_model'               => 'Samsung Galaxy S24',
                'device_code'                => 'SM-S921B',
                'cpu_architecture'           => 'arm64-v8a',
                'platform'                   => 'Android',
                'os_version'                 => 'Android 15',
                'sdk_version'                => 35,
                'app_version'                => '1.4.2',
                'app_build_number'           => 42,
                'screen_resolution'          => '1080 x 2340',
                'ip_address'                 => '103.21.124.55',
                'country'                    => 'India',
                'country_code'               => 'IN',
                'state'                      => 'Tamil Nadu',
                'city'                       => 'Tirunelveli',
                'latitude'                   => 8.7139,
                'longitude'                  => 77.7567,
                'timezone'                   => 'Asia/Kolkata',
                'language'                   => 'English',
                'permissions'                => [
                    'camera'        => 'granted',
                    'location'      => 'precise',
                    'notifications' => 'granted',
                    'photos_media'  => 'granted',
                ],
                'permissions_status'         => 'Camera + Location granted',
                'notification_status'        => 'Enabled',
                'fcm_token_updated_at'       => $now->copy()->subMinutes(18),
                'last_notification_delivered_at' => $now->copy()->subMinutes(12),
                'last_notification_opened_at'    => $now->copy()->subMinutes(10),
                'total_photos_taken'         => 142,
                'total_sessions_count'       => 28,
                'is_active'                  => true,
                'is_blacklisted'             => false,
                'first_installed_at'         => Carbon::parse('2026-08-18 10:24:00'),
                'last_active_at'             => $now->copy()->subMinutes(2),
            ],
            // 2. Tirunelveli - Pixel 8 Pro
            [
                'installation_id'            => 'INS-9C44E2',
                'firebase_installation_id'   => 'e8D4c3b2a1f5e6K3nP',
                'hardware_id'                => 'AND-PX8-112233445566',
                'fcm_token'                  => 'fcm_token_pixel_8_live_9c44e2_sample',
                'device_manufacturer'        => 'Google',
                'device_brand'               => 'Google',
                'device_model'               => 'Pixel 8 Pro',
                'device_code'                => 'GC3VE',
                'cpu_architecture'           => 'arm64-v8a',
                'platform'                   => 'Android',
                'os_version'                 => 'Android 15',
                'sdk_version'                => 35,
                'app_version'                => '1.4.2',
                'app_build_number'           => 42,
                'screen_resolution'          => '1344 x 2992',
                'ip_address'                 => '103.21.124.58',
                'country'                    => 'India',
                'country_code'               => 'IN',
                'state'                      => 'Tamil Nadu',
                'city'                       => 'Tirunelveli',
                'latitude'                   => 8.7280,
                'longitude'                  => 77.7420,
                'timezone'                   => 'Asia/Kolkata',
                'language'                   => 'English',
                'permissions'                => [
                    'camera'        => 'granted',
                    'location'      => 'precise',
                    'notifications' => 'granted',
                    'photos_media'  => 'granted',
                ],
                'permissions_status'         => 'Camera + Location granted',
                'notification_status'        => 'Enabled',
                'fcm_token_updated_at'       => $now->copy()->subHours(1),
                'last_notification_delivered_at' => $now->copy()->subHours(1),
                'last_notification_opened_at'    => $now->copy()->subMinutes(50),
                'total_photos_taken'         => 98,
                'total_sessions_count'       => 15,
                'is_active'                  => true,
                'is_blacklisted'             => false,
                'first_installed_at'         => Carbon::parse('2026-08-19 11:30:00'),
                'last_active_at'             => $now->copy()->subMinutes(8),
            ],
            // 3. Chennai - iPhone 16 Pro
            [
                'installation_id'            => 'INS-A7C3D9',
                'firebase_installation_id'   => 'd8A2b3c4d5e6f7L3nP',
                'hardware_id'                => 'IOS-IP16-443322110099',
                'fcm_token'                  => 'fcm_token_iphone_16_live_a7c3d9_gpscam_sample',
                'device_manufacturer'        => 'Apple',
                'device_brand'               => 'Apple',
                'device_model'               => 'iPhone 16 Pro',
                'device_code'                => 'iPhone16,2',
                'cpu_architecture'           => 'arm64e',
                'platform'                   => 'iOS',
                'os_version'                 => 'iOS 18.0',
                'sdk_version'                => 18,
                'app_version'                => '1.4.2',
                'app_build_number'           => 42,
                'screen_resolution'          => '1206 x 2622',
                'ip_address'                 => '157.48.112.44',
                'country'                    => 'India',
                'country_code'               => 'IN',
                'state'                      => 'Tamil Nadu',
                'city'                       => 'Chennai',
                'latitude'                   => 13.0827,
                'longitude'                  => 80.2707,
                'timezone'                   => 'Asia/Kolkata',
                'language'                   => 'English',
                'permissions'                => [
                    'camera'        => 'granted',
                    'location'      => 'precise',
                    'notifications' => 'granted',
                    'photos_media'  => 'granted',
                ],
                'permissions_status'         => 'Camera + Precise location',
                'notification_status'        => 'Enabled',
                'fcm_token_updated_at'       => $now->copy()->subMinutes(35),
                'last_notification_delivered_at' => $now->copy()->subMinutes(20),
                'last_notification_opened_at'    => $now->copy()->subMinutes(15),
                'total_photos_taken'         => 215,
                'total_sessions_count'       => 45,
                'is_active'                  => true,
                'is_blacklisted'             => false,
                'first_installed_at'         => Carbon::parse('2026-08-15 14:15:00'),
                'last_active_at'             => $now->copy()->subMinutes(5),
            ],
            // 4. Chennai - OnePlus 12
            [
                'installation_id'            => 'INS-C3F8D1',
                'firebase_installation_id'   => 'f9B4c2d1e7a6L5mQ',
                'hardware_id'                => 'AND-OP12-887766554433',
                'fcm_token'                  => 'fcm_token_oneplus_12_chennai_live_sample',
                'device_manufacturer'        => 'OnePlus',
                'device_brand'               => 'OnePlus',
                'device_model'               => 'OnePlus 12',
                'device_code'                => 'CPH2583',
                'cpu_architecture'           => 'arm64-v8a',
                'platform'                   => 'Android',
                'os_version'                 => 'Android 14',
                'sdk_version'                => 34,
                'app_version'                => '1.4.2',
                'app_build_number'           => 42,
                'screen_resolution'          => '1440 x 3168',
                'ip_address'                 => '157.48.112.90',
                'country'                    => 'India',
                'country_code'               => 'IN',
                'state'                      => 'Tamil Nadu',
                'city'                       => 'Chennai',
                'latitude'                   => 13.0475,
                'longitude'                  => 80.2090,
                'timezone'                   => 'Asia/Kolkata',
                'language'                   => 'English',
                'permissions'                => [
                    'camera'        => 'granted',
                    'location'      => 'precise',
                    'notifications' => 'granted',
                    'photos_media'  => 'granted',
                ],
                'permissions_status'         => 'Camera + Location granted',
                'notification_status'        => 'Enabled',
                'fcm_token_updated_at'       => $now->copy()->subHours(3),
                'last_notification_delivered_at' => $now->copy()->subHours(2),
                'last_notification_opened_at'    => $now->copy()->subHours(2),
                'total_photos_taken'         => 178,
                'total_sessions_count'       => 32,
                'is_active'                  => true,
                'is_blacklisted'             => false,
                'first_installed_at'         => Carbon::parse('2026-08-16 09:10:00'),
                'last_active_at'             => $now->copy()->subMinutes(25),
            ],
            // 5. Bengaluru - Galaxy S23 Ultra
            [
                'installation_id'            => 'INS-D4E9F2',
                'firebase_installation_id'   => 'a1B2c3d4e5f6g7h8',
                'hardware_id'                => 'AND-S23U-556677889900',
                'fcm_token'                  => 'fcm_token_s23u_bengaluru_sample',
                'device_manufacturer'        => 'Samsung',
                'device_brand'               => 'Samsung',
                'device_model'               => 'Galaxy S23 Ultra',
                'device_code'                => 'SM-S918B',
                'cpu_architecture'           => 'arm64-v8a',
                'platform'                   => 'Android',
                'os_version'                 => 'Android 14',
                'sdk_version'                => 34,
                'app_version'                => '1.4.2',
                'app_build_number'           => 42,
                'screen_resolution'          => '1440 x 3088',
                'ip_address'                 => '106.51.240.88',
                'country'                    => 'India',
                'country_code'               => 'IN',
                'state'                      => 'Karnataka',
                'city'                       => 'Bengaluru',
                'latitude'                   => 12.9716,
                'longitude'                  => 77.5946,
                'timezone'                   => 'Asia/Kolkata',
                'language'                   => 'English',
                'permissions'                => [
                    'camera'        => 'granted',
                    'location'      => 'precise',
                    'notifications' => 'granted',
                    'photos_media'  => 'granted',
                ],
                'permissions_status'         => 'Camera + Location granted',
                'notification_status'        => 'Enabled',
                'fcm_token_updated_at'       => $now->copy()->subHours(4),
                'last_notification_delivered_at' => $now->copy()->subHours(3),
                'last_notification_opened_at'    => $now->copy()->subHours(2),
                'total_photos_taken'         => 310,
                'total_sessions_count'       => 58,
                'is_active'                  => true,
                'is_blacklisted'             => false,
                'first_installed_at'         => Carbon::parse('2026-08-14 16:45:00'),
                'last_active_at'             => $now->copy()->subMinutes(14),
            ],
            // 6. New York - iPhone 15 Pro Max
            [
                'installation_id'            => 'INS-E5F6A7',
                'firebase_installation_id'   => 'b2C3d4e5f6g7h8i9',
                'hardware_id'                => 'IOS-IP15PM-998877661122',
                'fcm_token'                  => 'fcm_token_iphone_15pm_ny_sample',
                'device_manufacturer'        => 'Apple',
                'device_brand'               => 'Apple',
                'device_model'               => 'iPhone 15 Pro Max',
                'device_code'                => 'iPhone16,1',
                'cpu_architecture'           => 'arm64e',
                'platform'                   => 'iOS',
                'os_version'                 => 'iOS 17.5.1',
                'sdk_version'                => 17,
                'app_version'                => '1.4.2',
                'app_build_number'           => 42,
                'screen_resolution'          => '1290 x 2796',
                'ip_address'                 => '72.229.28.185',
                'country'                    => 'United States',
                'country_code'               => 'US',
                'state'                      => 'New York',
                'city'                       => 'New York',
                'latitude'                   => 40.7128,
                'longitude'                  => -74.0060,
                'timezone'                   => 'America/New_York',
                'language'                   => 'English',
                'permissions'                => [
                    'camera'        => 'granted',
                    'location'      => 'precise',
                    'notifications' => 'granted',
                    'photos_media'  => 'granted',
                ],
                'permissions_status'         => 'Camera + Location granted',
                'notification_status'        => 'Enabled',
                'fcm_token_updated_at'       => $now->copy()->subMinutes(50),
                'last_notification_delivered_at' => $now->copy()->subMinutes(40),
                'last_notification_opened_at'    => $now->copy()->subMinutes(30),
                'total_photos_taken'         => 240,
                'total_sessions_count'       => 42,
                'is_active'                  => true,
                'is_blacklisted'             => false,
                'first_installed_at'         => Carbon::parse('2026-08-12 18:20:00'),
                'last_active_at'             => $now->copy()->subMinutes(6),
            ],
            // 7. São Paulo - Xiaomi 14
            [
                'installation_id'            => 'INS-B1D8F4',
                'firebase_installation_id'   => 'e9B3c4d5e6f7a8M4oQ',
                'hardware_id'                => 'AND-XM14-112233445566',
                'fcm_token'                  => 'fcm_token_xiaomi_14_live_b1d8f4_gpscam_sample',
                'device_manufacturer'        => 'Xiaomi',
                'device_brand'               => 'Xiaomi',
                'device_model'               => 'Xiaomi 14',
                'device_code'                => '23127PN0CG',
                'cpu_architecture'           => 'arm64-v8a',
                'platform'                   => 'Android',
                'os_version'                 => 'Android 14',
                'sdk_version'                => 34,
                'app_version'                => '1.4.1',
                'app_build_number'           => 41,
                'screen_resolution'          => '1200 x 2670',
                'ip_address'                 => '177.136.240.12',
                'country'                    => 'Brazil',
                'country_code'               => 'BR',
                'state'                      => 'São Paulo',
                'city'                       => 'São Paulo',
                'latitude'                   => -23.5505,
                'longitude'                  => -46.6333,
                'timezone'                   => 'America/Sao_Paulo',
                'language'                   => 'Portuguese',
                'permissions'                => [
                    'camera'        => 'granted',
                    'location'      => 'approximate',
                    'notifications' => 'granted',
                    'photos_media'  => 'granted',
                ],
                'permissions_status'         => 'Camera + Approx. location',
                'notification_status'        => 'Enabled',
                'fcm_token_updated_at'       => $now->copy()->subHours(2),
                'last_notification_delivered_at' => $now->copy()->subHours(1),
                'last_notification_opened_at'    => $now->copy()->subMinutes(45),
                'total_photos_taken'         => 84,
                'total_sessions_count'       => 18,
                'is_active'                  => true,
                'is_blacklisted'             => false,
                'first_installed_at'         => Carbon::parse('2026-08-17 09:20:00'),
                'last_active_at'             => $now->copy()->subMinutes(12),
            ],
            // 8. London - iPhone 15
            [
                'installation_id'            => 'INS-F7G8H9',
                'firebase_installation_id'   => 'c3D4e5f6g7h8i9j0',
                'hardware_id'                => 'IOS-IP15-776655443322',
                'fcm_token'                  => 'fcm_token_iphone_15_london_sample',
                'device_manufacturer'        => 'Apple',
                'device_brand'               => 'Apple',
                'device_model'               => 'iPhone 15',
                'device_code'                => 'iPhone15,4',
                'cpu_architecture'           => 'arm64e',
                'platform'                   => 'iOS',
                'os_version'                 => 'iOS 17.4.1',
                'sdk_version'                => 17,
                'app_version'                => '1.4.2',
                'app_build_number'           => 42,
                'screen_resolution'          => '1179 x 2556',
                'ip_address'                 => '82.165.197.1',
                'country'                    => 'United Kingdom',
                'country_code'               => 'GB',
                'state'                      => 'England',
                'city'                       => 'London',
                'latitude'                   => 51.5074,
                'longitude'                  => -0.1278,
                'timezone'                   => 'Europe/London',
                'language'                   => 'English',
                'permissions'                => [
                    'camera'        => 'granted',
                    'location'      => 'precise',
                    'notifications' => 'granted',
                    'photos_media'  => 'granted',
                ],
                'permissions_status'         => 'Camera + Location granted',
                'notification_status'        => 'Enabled',
                'fcm_token_updated_at'       => $now->copy()->subHours(5),
                'last_notification_delivered_at' => $now->copy()->subHours(4),
                'last_notification_opened_at'    => $now->copy()->subHours(3),
                'total_photos_taken'         => 165,
                'total_sessions_count'       => 29,
                'is_active'                  => true,
                'is_blacklisted'             => false,
                'first_installed_at'         => Carbon::parse('2026-08-11 10:15:00'),
                'last_active_at'             => $now->copy()->subMinutes(18),
            ],
            // 9. Dubai - Galaxy S24+
            [
                'installation_id'            => 'INS-G8H9J0',
                'firebase_installation_id'   => 'd4E5f6g7h8i9j0k1',
                'hardware_id'                => 'AND-S24P-334455667788',
                'fcm_token'                  => 'fcm_token_s24p_dubai_sample',
                'device_manufacturer'        => 'Samsung',
                'device_brand'               => 'Samsung',
                'device_model'               => 'Galaxy S24+',
                'device_code'                => 'SM-S926B',
                'cpu_architecture'           => 'arm64-v8a',
                'platform'                   => 'Android',
                'os_version'                 => 'Android 15',
                'sdk_version'                => 35,
                'app_version'                => '1.4.2',
                'app_build_number'           => 42,
                'screen_resolution'          => '1440 x 3120',
                'ip_address'                 => '185.193.64.1',
                'country'                    => 'UAE',
                'country_code'               => 'AE',
                'state'                      => 'Dubai',
                'city'                       => 'Dubai',
                'latitude'                   => 25.2048,
                'longitude'                  => 55.2708,
                'timezone'                   => 'Asia/Dubai',
                'language'                   => 'Arabic',
                'permissions'                => [
                    'camera'        => 'granted',
                    'location'      => 'precise',
                    'notifications' => 'granted',
                    'photos_media'  => 'granted',
                ],
                'permissions_status'         => 'Camera + Location granted',
                'notification_status'        => 'Enabled',
                'fcm_token_updated_at'       => $now->copy()->subHours(6),
                'last_notification_delivered_at' => $now->copy()->subHours(5),
                'last_notification_opened_at'    => $now->copy()->subHours(4),
                'total_photos_taken'         => 192,
                'total_sessions_count'       => 35,
                'is_active'                  => true,
                'is_blacklisted'             => false,
                'first_installed_at'         => Carbon::parse('2026-08-10 12:00:00'),
                'last_active_at'             => $now->copy()->subMinutes(30),
            ],
            // 10. Jakarta - Oppo Find X7
            [
                'installation_id'            => 'INS-H9J0K1',
                'firebase_installation_id'   => 'e5F6g7h8i9j0k1l2',
                'hardware_id'                => 'AND-OPFIND-990011223344',
                'fcm_token'                  => 'fcm_token_oppo_jakarta_sample',
                'device_manufacturer'        => 'Oppo',
                'device_brand'               => 'Oppo',
                'device_model'               => 'Find X7 Ultra',
                'device_code'                => 'PHY110',
                'cpu_architecture'           => 'arm64-v8a',
                'platform'                   => 'Android',
                'os_version'                 => 'Android 14',
                'sdk_version'                => 34,
                'app_version'                => '1.4.2',
                'app_build_number'           => 42,
                'screen_resolution'          => '1440 x 3168',
                'ip_address'                 => '180.252.164.1',
                'country'                    => 'Indonesia',
                'country_code'               => 'ID',
                'state'                      => 'Jakarta',
                'city'                       => 'Jakarta',
                'latitude'                   => -6.2088,
                'longitude'                  => 106.8456,
                'timezone'                   => 'Asia/Jakarta',
                'language'                   => 'Indonesian',
                'permissions'                => [
                    'camera'        => 'granted',
                    'location'      => 'precise',
                    'notifications' => 'granted',
                    'photos_media'  => 'granted',
                ],
                'permissions_status'         => 'Camera + Location granted',
                'notification_status'        => 'Enabled',
                'fcm_token_updated_at'       => $now->copy()->subHours(7),
                'last_notification_delivered_at' => $now->copy()->subHours(6),
                'last_notification_opened_at'    => $now->copy()->subHours(5),
                'total_photos_taken'         => 115,
                'total_sessions_count'       => 22,
                'is_active'                  => true,
                'is_blacklisted'             => false,
                'first_installed_at'         => Carbon::parse('2026-08-09 08:30:00'),
                'last_active_at'             => $now->copy()->subMinutes(40),
            ],
        ];

        foreach ($devices as $data) {
            Device::updateOrCreate(
                ['installation_id' => $data['installation_id']],
                $data
            );
        }
    }
}
