<?php

namespace Database\Seeders;

use App\Models\Location;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        // 7x24 Activity Matrix for Tirunelveli (Mon-Sun x 0-23 hours)
        // Values from 0 to 10 (0 = lowest/empty, 10 = max peak Sunday 7 PM)
        $tirunelveliMatrix = [
            'Mon' => [0,0,0,0,1,1,2,3,4,4,5,5,4,4,5,6,7,7,8,7,6,4,2,1],
            'Tue' => [0,0,0,0,1,1,2,3,4,4,5,5,4,4,5,6,7,7,8,7,6,4,2,1],
            'Wed' => [0,0,0,0,1,1,2,3,4,5,5,5,5,4,5,6,7,8,8,7,6,4,2,1],
            'Thu' => [0,0,0,0,1,1,2,3,4,5,5,5,5,5,6,6,7,8,8,8,6,4,2,1],
            'Fri' => [0,0,0,0,1,1,2,3,4,5,6,6,5,5,6,7,8,8,9,8,7,5,3,1],
            'Sat' => [0,0,0,0,1,2,3,4,5,6,7,7,6,6,7,8,8,9,9,9,8,6,4,2],
            'Sun' => [0,0,0,0,1,2,3,4,5,6,7,8,7,7,8,9,9,10,10,9,8,6,4,2], // Peak 7 PM (Index 19)
        ];

        $locations = [
            [
                'city'                            => 'Tirunelveli',
                'state'                           => 'Tamil Nadu',
                'country'                         => 'India',
                'country_code'                    => 'IN',
                'latitude'                        => 8.7139,
                'longitude'                       => 77.7567,
                'timezone'                        => 'Asia/Kolkata (IST)',
                'location_level'                  => 'City',
                'location_source'                 => 'GPS + Network',
                'status'                          => 'High Activity',
                'anonymous_users_count'           => 8426,
                'devices_count'                   => 9184,
                'photos_captured_count'           => 42680,
                'new_installs_count'              => 618,
                'notification_enabled_percentage' => 76.80,
                'location_sources'                => [
                    'gps'         => 68,
                    'network'     => 24,
                    'approximate' => 8,
                ],
                'permission_breakdown'            => [
                    'precise'     => 62,
                    'approximate' => 21,
                    'denied'      => 17,
                ],
                'platform_distribution'           => [
                    'android' => 91,
                    'ios'     => 9,
                ],
                'top_app_versions'                => [
                    'v1.4.2' => 48,
                    'v1.4.1' => 31,
                    'v1.4.0' => 14,
                    'older'  => 7,
                ],
                'activity_areas'                  => [
                    [
                        'name'       => 'Palayamkottai',
                        'lat'        => 8.7150,
                        'lng'        => 77.7400,
                        'count'      => '2.4K',
                        'raw_count'  => 2418,
                        'percentage' => 24.8,
                        'level'      => 'high',
                    ],
                    [
                        'name'       => 'Tirunelveli Junction',
                        'lat'        => 8.7300,
                        'lng'        => 77.7100,
                        'count'      => '1.8K',
                        'raw_count'  => 1846,
                        'percentage' => 18.6,
                        'level'      => 'medium-high',
                    ],
                    [
                        'name'       => 'Vannarpettai',
                        'lat'        => 8.7240,
                        'lng'        => 77.7280,
                        'count'      => '1.5K',
                        'raw_count'  => 1532,
                        'percentage' => 15.3,
                        'level'      => 'medium-high',
                    ],
                    [
                        'name'       => 'Melapalayam',
                        'lat'        => 8.6980,
                        'lng'        => 77.7180,
                        'count'      => '980',
                        'raw_count'  => 984,
                        'percentage' => 9.8,
                        'level'      => 'medium',
                    ],
                    [
                        'name'       => 'High Ground',
                        'lat'        => 8.7040,
                        'lng'        => 77.7520,
                        'count'      => '720',
                        'raw_count'  => 722,
                        'percentage' => 7.2,
                        'level'      => 'low',
                    ],
                ],
                'activity_by_hour_matrix'         => $tirunelveliMatrix,
                'activity_types'                  => [
                    'photo_capture'  => 54,
                    'photo_save'     => 23,
                    'location_stamp' => 15,
                    'share'          => 8,
                ],
                'daily_pattern'                   => [9800, 11200, 12400, 13800, 14900, 16500, 18900],
                'peak_hour'                       => '7 PM',
                'peak_day'                        => 'Sunday',
                'top_area_name'                   => 'Palayamkottai',
                'last_activity_at'                => $now->copy()->subMinutes(2),
            ],
            [
                'city'                            => 'Chennai',
                'state'                           => 'Tamil Nadu',
                'country'                         => 'India',
                'country_code'                    => 'IN',
                'latitude'                        => 13.0827,
                'longitude'                       => 80.2707,
                'timezone'                        => 'Asia/Kolkata (IST)',
                'location_level'                  => 'City',
                'location_source'                 => 'GPS + Network',
                'status'                          => 'High Activity',
                'anonymous_users_count'           => 18940,
                'devices_count'                   => 20215,
                'photos_captured_count'           => 98420,
                'new_installs_count'              => 1284,
                'notification_enabled_percentage' => 81.20,
                'location_sources'                => ['gps' => 72, 'network' => 20, 'approximate' => 8],
                'permission_breakdown'            => ['precise' => 68, 'approximate' => 20, 'denied' => 12],
                'platform_distribution'           => ['android' => 88, 'ios' => 12],
                'top_app_versions'                => ['v1.4.2' => 52, 'v1.4.1' => 30, 'v1.4.0' => 12, 'older' => 6],
                'activity_areas'                  => [
                    ['name' => 'T. Nagar', 'lat' => 13.0418, 'lng' => 80.2341, 'count' => '5.2K', 'raw_count' => 5200, 'percentage' => 28.0, 'level' => 'high'],
                    ['name' => 'Adyar', 'lat' => 13.0012, 'lng' => 80.2565, 'count' => '4.1K', 'raw_count' => 4100, 'percentage' => 22.0, 'level' => 'medium-high'],
                    ['name' => 'Anna Nagar', 'lat' => 13.0850, 'lng' => 80.2100, 'count' => '3.8K', 'raw_count' => 3800, 'percentage' => 20.5, 'level' => 'medium-high'],
                ],
                'activity_by_hour_matrix'         => $tirunelveliMatrix,
                'activity_types'                  => ['photo_capture' => 56, 'photo_save' => 22, 'location_stamp' => 14, 'share' => 8],
                'daily_pattern'                   => [21000, 23500, 25200, 28100, 31000, 34200, 39500],
                'peak_hour'                       => '8 PM',
                'peak_day'                        => 'Saturday',
                'top_area_name'                   => 'T. Nagar',
                'last_activity_at'                => $now->copy()->subMinutes(3),
            ],
            [
                'city'                            => 'Bengaluru',
                'state'                           => 'Karnataka',
                'country'                         => 'India',
                'country_code'                    => 'IN',
                'latitude'                        => 12.9716,
                'longitude'                       => 77.5946,
                'timezone'                        => 'Asia/Kolkata (IST)',
                'location_level'                  => 'City',
                'location_source'                 => 'GPS + Network',
                'status'                          => 'High Activity',
                'anonymous_users_count'           => 16582,
                'devices_count'                   => 17904,
                'photos_captured_count'           => 84360,
                'new_installs_count'              => 1126,
                'notification_enabled_percentage' => 79.50,
                'location_sources'                => ['gps' => 70, 'network' => 22, 'approximate' => 8],
                'permission_breakdown'            => ['precise' => 65, 'approximate' => 22, 'denied' => 13],
                'platform_distribution'           => ['android' => 85, 'ios' => 15],
                'top_app_versions'                => ['v1.4.2' => 50, 'v1.4.1' => 32, 'v1.4.0' => 12, 'older' => 6],
                'activity_areas'                  => [
                    ['name' => 'Koramangala', 'lat' => 12.9352, 'lng' => 77.6245, 'count' => '4.8K', 'raw_count' => 4800, 'percentage' => 26.5, 'level' => 'high'],
                    ['name' => 'Indiranagar', 'lat' => 12.9784, 'lng' => 77.6408, 'count' => '3.9K', 'raw_count' => 3900, 'percentage' => 21.5, 'level' => 'medium-high'],
                ],
                'activity_by_hour_matrix'         => $tirunelveliMatrix,
                'activity_types'                  => ['photo_capture' => 52, 'photo_save' => 24, 'location_stamp' => 16, 'share' => 8],
                'daily_pattern'                   => [18500, 20100, 22400, 24800, 27500, 30200, 35100],
                'peak_hour'                       => '6 PM',
                'peak_day'                        => 'Sunday',
                'top_area_name'                   => 'Koramangala',
                'last_activity_at'                => $now->copy()->subMinutes(5),
            ],
            [
                'city'                            => 'New York',
                'state'                           => 'New York',
                'country'                         => 'United States',
                'country_code'                    => 'US',
                'latitude'                        => 40.7128,
                'longitude'                       => -74.0060,
                'timezone'                        => 'America/New_York (EST)',
                'location_level'                  => 'City',
                'location_source'                 => 'Network + GPS',
                'status'                          => 'Active',
                'anonymous_users_count'           => 12840,
                'devices_count'                   => 13522,
                'photos_captured_count'           => 58470,
                'new_installs_count'              => 742,
                'notification_enabled_percentage' => 74.30,
                'location_sources'                => ['gps' => 60, 'network' => 32, 'approximate' => 8],
                'permission_breakdown'            => ['precise' => 58, 'approximate' => 26, 'denied' => 16],
                'platform_distribution'           => ['android' => 45, 'ios' => 55],
                'top_app_versions'                => ['v1.4.2' => 55, 'v1.4.1' => 30, 'v1.4.0' => 10, 'older' => 5],
                'activity_areas'                  => [
                    ['name' => 'Manhattan', 'lat' => 40.7831, 'lng' => -73.9712, 'count' => '4.2K', 'raw_count' => 4200, 'percentage' => 32.0, 'level' => 'high'],
                    ['name' => 'Brooklyn', 'lat' => 40.6782, 'lng' => -73.9442, 'count' => '3.1K', 'raw_count' => 3100, 'percentage' => 24.0, 'level' => 'medium-high'],
                ],
                'activity_by_hour_matrix'         => $tirunelveliMatrix,
                'activity_types'                  => ['photo_capture' => 50, 'photo_save' => 25, 'location_stamp' => 15, 'share' => 10],
                'daily_pattern'                   => [12000, 13400, 14500, 16000, 17800, 19500, 22100],
                'peak_hour'                       => '5 PM',
                'peak_day'                        => 'Saturday',
                'top_area_name'                   => 'Manhattan',
                'last_activity_at'                => $now->copy()->subMinutes(6),
            ],
            [
                'city'                            => 'São Paulo',
                'state'                           => 'São Paulo',
                'country'                         => 'Brazil',
                'country_code'                    => 'BR',
                'latitude'                        => -23.5505,
                'longitude'                       => -46.6333,
                'timezone'                        => 'America/Sao_Paulo (BRT)',
                'location_level'                  => 'City',
                'location_source'                 => 'GPS + Network',
                'status'                          => 'Active',
                'anonymous_users_count'           => 9418,
                'devices_count'                   => 10106,
                'photos_captured_count'           => 41230,
                'new_installs_count'              => 608,
                'notification_enabled_percentage' => 71.50,
                'location_sources'                => ['gps' => 64, 'network' => 28, 'approximate' => 8],
                'permission_breakdown'            => ['precise' => 55, 'approximate' => 28, 'denied' => 17],
                'platform_distribution'           => ['android' => 86, 'ios' => 14],
                'top_app_versions'                => ['v1.4.2' => 45, 'v1.4.1' => 34, 'v1.4.0' => 14, 'older' => 7],
                'activity_areas'                  => [
                    ['name' => 'Paulista Ave', 'lat' => -23.5615, 'lng' => -46.6560, 'count' => '2.9K', 'raw_count' => 2900, 'percentage' => 31.0, 'level' => 'high'],
                ],
                'activity_by_hour_matrix'         => $tirunelveliMatrix,
                'activity_types'                  => ['photo_capture' => 52, 'photo_save' => 24, 'location_stamp' => 16, 'share' => 8],
                'daily_pattern'                   => [8900, 9800, 10500, 11400, 12600, 14100, 16200],
                'peak_hour'                       => '7 PM',
                'peak_day'                        => 'Friday',
                'top_area_name'                   => 'Paulista Ave',
                'last_activity_at'                => $now->copy()->subMinutes(9),
            ],
            [
                'city'                            => 'Jakarta',
                'state'                           => 'Jakarta',
                'country'                         => 'Indonesia',
                'country_code'                    => 'ID',
                'latitude'                        => -6.2088,
                'longitude'                       => 106.8456,
                'timezone'                        => 'Asia/Jakarta (WIB)',
                'location_level'                  => 'City',
                'location_source'                 => 'GPS + Network',
                'status'                          => 'Active',
                'anonymous_users_count'           => 8925,
                'devices_count'                   => 9640,
                'photos_captured_count'           => 38915,
                'new_installs_count'              => 572,
                'notification_enabled_percentage' => 75.00,
                'location_sources'                => ['gps' => 66, 'network' => 26, 'approximate' => 8],
                'permission_breakdown'            => ['precise' => 60, 'approximate' => 24, 'denied' => 16],
                'platform_distribution'           => ['android' => 92, 'ios' => 8],
                'top_app_versions'                => ['v1.4.2' => 47, 'v1.4.1' => 32, 'v1.4.0' => 14, 'older' => 7],
                'activity_areas'                  => [
                    ['name' => 'Central Jakarta', 'lat' => -6.1865, 'lng' => 106.8341, 'count' => '2.7K', 'raw_count' => 2700, 'percentage' => 30.0, 'level' => 'high'],
                ],
                'activity_by_hour_matrix'         => $tirunelveliMatrix,
                'activity_types'                  => ['photo_capture' => 55, 'photo_save' => 23, 'location_stamp' => 14, 'share' => 8],
                'daily_pattern'                   => [8200, 9100, 9900, 10800, 11900, 13200, 15400],
                'peak_hour'                       => '6 PM',
                'peak_day'                        => 'Saturday',
                'top_area_name'                   => 'Central Jakarta',
                'last_activity_at'                => $now->copy()->subMinutes(12),
            ],
            [
                'city'                            => 'London',
                'state'                           => 'England',
                'country'                         => 'United Kingdom',
                'country_code'                    => 'GB',
                'latitude'                        => 51.5074,
                'longitude'                       => -0.1278,
                'timezone'                        => 'Europe/London (GMT)',
                'location_level'                  => 'City',
                'location_source'                 => 'Network + GPS',
                'status'                          => 'Active',
                'anonymous_users_count'           => 7204,
                'devices_count'                   => 7886,
                'photos_captured_count'           => 32410,
                'new_installs_count'              => 484,
                'notification_enabled_percentage' => 77.20,
                'location_sources'                => ['gps' => 58, 'network' => 34, 'approximate' => 8],
                'permission_breakdown'            => ['precise' => 59, 'approximate' => 25, 'denied' => 16],
                'platform_distribution'           => ['android' => 52, 'ios' => 48],
                'top_app_versions'                => ['v1.4.2' => 54, 'v1.4.1' => 30, 'v1.4.0' => 11, 'older' => 5],
                'activity_areas'                  => [
                    ['name' => 'Westminster', 'lat' => 51.4975, 'lng' => -0.1357, 'count' => '2.5K', 'raw_count' => 2500, 'percentage' => 34.0, 'level' => 'high'],
                ],
                'activity_by_hour_matrix'         => $tirunelveliMatrix,
                'activity_types'                  => ['photo_capture' => 51, 'photo_save' => 24, 'location_stamp' => 16, 'share' => 9],
                'daily_pattern'                   => [7100, 7800, 8400, 9200, 10100, 11300, 13100],
                'peak_hour'                       => '5 PM',
                'peak_day'                        => 'Sunday',
                'top_area_name'                   => 'Westminster',
                'last_activity_at'                => $now->copy()->subMinutes(15),
            ],
            [
                'city'                            => 'Dubai',
                'state'                           => 'Dubai',
                'country'                         => 'UAE',
                'country_code'                    => 'AE',
                'latitude'                        => 25.2048,
                'longitude'                       => 55.2708,
                'timezone'                        => 'Asia/Dubai (GST)',
                'location_level'                  => 'City',
                'location_source'                 => 'GPS + Network',
                'status'                          => 'Active',
                'anonymous_users_count'           => 5186,
                'devices_count'                   => 5714,
                'photos_captured_count'           => 24860,
                'new_installs_count'              => 362,
                'notification_enabled_percentage' => 82.40,
                'location_sources'                => ['gps' => 74, 'network' => 18, 'approximate' => 8],
                'permission_breakdown'            => ['precise' => 70, 'approximate' => 18, 'denied' => 12],
                'platform_distribution'           => ['android' => 60, 'ios' => 40],
                'top_app_versions'                => ['v1.4.2' => 58, 'v1.4.1' => 28, 'v1.4.0' => 10, 'older' => 4],
                'activity_areas'                  => [
                    ['name' => 'Downtown Dubai', 'lat' => 25.1972, 'lng' => 55.2744, 'count' => '2.1K', 'raw_count' => 2100, 'percentage' => 38.0, 'level' => 'high'],
                ],
                'activity_by_hour_matrix'         => $tirunelveliMatrix,
                'activity_types'                  => ['photo_capture' => 58, 'photo_save' => 22, 'location_stamp' => 12, 'share' => 8],
                'daily_pattern'                   => [5200, 5800, 6400, 7100, 8000, 9200, 10800],
                'peak_hour'                       => '8 PM',
                'peak_day'                        => 'Saturday',
                'top_area_name'                   => 'Downtown Dubai',
                'last_activity_at'                => $now->copy()->subMinutes(18),
            ],
        ];

        foreach ($locations as $data) {
            Location::updateOrCreate(
                ['city' => $data['city'], 'country' => $data['country']],
                $data
            );
        }

        // Dynamically sync metrics from all installed devices
        app(\App\Services\LocationService::class)->syncAllFromDevices();
    }
}
