<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\NotificationCampaign;
use App\Models\AudienceSegment;
use App\Models\User;
use Carbon\Carbon;

class NotificationCampaignSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin = User::first();
        $adminId = $admin ? $admin->id : null;
        $segment = AudienceSegment::first();
        $segmentId = $segment ? $segment->id : null;

        $campaigns = [
            [
                'campaign_id'         => 'NTF-2026-0128',
                'name'                => 'GPS Camera Feature Update',
                'title'               => 'GPS Camera Update',
                'message'             => 'New GPS Camera features are now available. Explore improved location stamps and better performance.',
                'action'              => 'Open App',
                'audience_type'       => 'individual',
                'audience_label'      => 'Individual Devices • 3',
                'segment_id'          => $segmentId,
                'target_device_ids'   => ['ANON-DEVICE-001', 'ANON-DEVICE-002', 'ANON-DEVICE-003'],
                'android_count'       => 2,
                'ios_count'           => 1,
                'total_audience'      => 3,
                'delivered_count'     => 0,
                'open_count'          => 0,
                'open_rate'           => null,
                'status'              => 'scheduled',
                'scheduled_at'        => Carbon::parse('2026-08-26 10:30:00'),
                'sent_at'             => null,
                'time_zone'           => 'Asia/Kolkata',
                'quiet_hours_enabled' => true,
                'expiry_hours'        => 24,
                'timeline_steps'      => [
                    ['title' => 'Draft Created', 'time' => '24 Aug 2026, 09:45 AM', 'done' => true, 'icon' => 'fa-regular fa-file-lines'],
                    ['title' => 'Audience Selected', 'time' => '24 Aug 2026, 09:55 AM', 'done' => true, 'icon' => 'fa-solid fa-users'],
                    ['title' => 'Scheduled', 'time' => '24 Aug 2026, 10:00 AM', 'done' => true, 'icon' => 'fa-regular fa-calendar'],
                    ['title' => 'Awaiting Delivery', 'time' => '26 Aug 2026, 10:30 AM', 'done' => false, 'icon' => 'fa-regular fa-clock'],
                ],
                'created_by'          => $adminId,
                'created_at'          => Carbon::parse('2026-08-24 10:00:00'),
                'updated_at'          => Carbon::parse('2026-08-24 10:00:00'),
            ],
            [
                'campaign_id'         => 'NTF-2026-0127',
                'name'                => 'New Map Styles Available',
                'title'               => 'Explore New GPS Map Themes',
                'message'             => 'We have added satellite, hybrid and terrain styling to your photo stamps. Check them out today!',
                'action'              => 'Open App',
                'audience_type'       => 'all',
                'audience_label'      => 'All Eligible Installations • 7,054',
                'segment_id'          => null,
                'target_device_ids'   => null,
                'android_count'       => 6419,
                'ios_count'           => 635,
                'total_audience'      => 7054,
                'delivered_count'     => 6842,
                'open_count'          => 2928,
                'open_rate'           => 42.80,
                'status'              => 'sent',
                'scheduled_at'        => Carbon::parse('2026-08-23 09:00:00'),
                'sent_at'             => Carbon::parse('2026-08-23 09:00:00'),
                'time_zone'           => 'Asia/Kolkata',
                'quiet_hours_enabled' => true,
                'expiry_hours'        => 24,
                'timeline_steps'      => [
                    ['title' => 'Draft Created', 'time' => '22 Aug 2026, 09:00 AM', 'done' => true, 'icon' => 'fa-regular fa-file-lines'],
                    ['title' => 'Audience Selected', 'time' => '22 Aug 2026, 09:10 AM', 'done' => true, 'icon' => 'fa-solid fa-users'],
                    ['title' => 'Scheduled', 'time' => '22 Aug 2026, 09:15 AM', 'done' => true, 'icon' => 'fa-regular fa-calendar'],
                    ['title' => 'Delivered', 'time' => '23 Aug 2026, 09:00 AM', 'done' => true, 'icon' => 'fa-solid fa-check'],
                ],
                'created_by'          => $adminId,
                'created_at'          => Carbon::parse('2026-08-22 09:00:00'),
                'updated_at'          => Carbon::parse('2026-08-23 09:00:00'),
            ],
            [
                'campaign_id'         => 'NTF-2026-0126',
                'name'                => 'Location Stamp Tips',
                'title'               => 'Get High Accuracy GPS Coordinates',
                'message'             => 'Learn how to calibrate your camera sensors for pinpoint geotag precision in every capture.',
                'action'              => 'Open App',
                'audience_type'       => 'segment',
                'audience_label'      => 'Tirunelveli Active Users • 1,284',
                'segment_id'          => $segmentId,
                'target_device_ids'   => null,
                'android_count'       => 1168,
                'ios_count'           => 116,
                'total_audience'      => 1284,
                'delivered_count'     => 1241,
                'open_count'          => 635,
                'open_rate'           => 51.20,
                'status'              => 'sent',
                'scheduled_at'        => Carbon::parse('2026-08-21 18:30:00'),
                'sent_at'             => Carbon::parse('2026-08-21 18:30:00'),
                'time_zone'           => 'Asia/Kolkata',
                'quiet_hours_enabled' => true,
                'expiry_hours'        => 24,
                'timeline_steps'      => [
                    ['title' => 'Draft Created', 'time' => '20 Aug 2026, 11:15 AM', 'done' => true, 'icon' => 'fa-regular fa-file-lines'],
                    ['title' => 'Audience Selected', 'time' => '20 Aug 2026, 11:20 AM', 'done' => true, 'icon' => 'fa-solid fa-users'],
                    ['title' => 'Scheduled', 'time' => '20 Aug 2026, 11:25 AM', 'done' => true, 'icon' => 'fa-regular fa-calendar'],
                    ['title' => 'Delivered', 'time' => '21 Aug 2026, 06:30 PM', 'done' => true, 'icon' => 'fa-solid fa-check'],
                ],
                'created_by'          => $adminId,
                'created_at'          => Carbon::parse('2026-08-20 11:15:00'),
                'updated_at'          => Carbon::parse('2026-08-21 18:30:00'),
            ],
            [
                'campaign_id'         => 'NTF-2026-0125',
                'name'                => 'Weekend Feature Highlight',
                'title'               => 'Weekend Photo Stamps & Overlays',
                'message'             => 'Capture your weekend travels with customizable time & altitude watermarks.',
                'action'              => 'Open App',
                'audience_type'       => 'segment',
                'audience_label'      => 'Audience Segment • 2,190',
                'segment_id'          => $segmentId,
                'target_device_ids'   => null,
                'android_count'       => 1993,
                'ios_count'           => 197,
                'total_audience'      => 2190,
                'delivered_count'     => 0,
                'open_count'          => 0,
                'open_rate'           => null,
                'status'              => 'draft',
                'scheduled_at'        => null,
                'sent_at'             => null,
                'time_zone'           => 'Asia/Kolkata',
                'quiet_hours_enabled' => true,
                'expiry_hours'        => 24,
                'timeline_steps'      => [
                    ['title' => 'Draft Created', 'time' => '19 Aug 2026, 02:00 PM', 'done' => true, 'icon' => 'fa-regular fa-file-lines'],
                    ['title' => 'Audience Selected', 'time' => '19 Aug 2026, 02:05 PM', 'done' => true, 'icon' => 'fa-solid fa-users'],
                ],
                'created_by'          => $adminId,
                'created_at'          => Carbon::parse('2026-08-19 14:00:00'),
                'updated_at'          => Carbon::parse('2026-08-19 14:00:00'),
            ],
            [
                'campaign_id'         => 'NTF-2026-0124',
                'name'                => 'Critical App Update',
                'title'               => 'Important Fix Available for Android',
                'message'             => 'Please update your GPS Camera app to continue receiving automated geotag synchronization.',
                'action'              => 'Open App',
                'audience_type'       => 'segment',
                'audience_label'      => 'Android v1.3 and below • 984',
                'segment_id'          => $segmentId,
                'target_device_ids'   => null,
                'android_count'       => 984,
                'ios_count'           => 0,
                'total_audience'      => 984,
                'delivered_count'     => 0,
                'open_count'          => 0,
                'open_rate'           => 0.00,
                'status'              => 'failed',
                'scheduled_at'        => Carbon::parse('2026-08-18 11:15:00'),
                'sent_at'             => Carbon::parse('2026-08-18 11:15:00'),
                'time_zone'           => 'Asia/Kolkata',
                'quiet_hours_enabled' => true,
                'expiry_hours'        => 24,
                'timeline_steps'      => [
                    ['title' => 'Draft Created', 'time' => '18 Aug 2026, 10:00 AM', 'done' => true, 'icon' => 'fa-regular fa-file-lines'],
                    ['title' => 'Audience Selected', 'time' => '18 Aug 2026, 10:15 AM', 'done' => true, 'icon' => 'fa-solid fa-users'],
                    ['title' => 'Scheduled', 'time' => '18 Aug 2026, 10:30 AM', 'done' => true, 'icon' => 'fa-regular fa-calendar'],
                    ['title' => 'Dispatch Failed', 'time' => '18 Aug 2026, 11:15 AM', 'done' => false, 'icon' => 'fa-solid fa-triangle-exclamation'],
                ],
                'created_by'          => $adminId,
                'created_at'          => Carbon::parse('2026-08-18 10:00:00'),
                'updated_at'          => Carbon::parse('2026-08-18 11:15:00'),
            ],
            [
                'campaign_id'         => 'NTF-2026-0123',
                'name'                => 'Storage Permission Reminder',
                'title'               => 'Ensure Camera Photos are Saved',
                'message'             => 'Grant storage permissions to automatically save HD watermarked pictures to your gallery.',
                'action'              => 'Open App',
                'audience_type'       => 'segment',
                'audience_label'      => 'Location: Chennai • 862',
                'segment_id'          => $segmentId,
                'target_device_ids'   => null,
                'android_count'       => 784,
                'ios_count'           => 78,
                'total_audience'      => 862,
                'delivered_count'     => 831,
                'open_count'          => 321,
                'open_rate'           => 38.60,
                'status'              => 'sent',
                'scheduled_at'        => Carbon::parse('2026-08-16 16:00:00'),
                'sent_at'             => Carbon::parse('2026-08-16 16:00:00'),
                'time_zone'           => 'Asia/Kolkata',
                'quiet_hours_enabled' => true,
                'expiry_hours'        => 24,
                'timeline_steps'      => [
                    ['title' => 'Draft Created', 'time' => '15 Aug 2026, 09:30 AM', 'done' => true, 'icon' => 'fa-regular fa-file-lines'],
                    ['title' => 'Audience Selected', 'time' => '15 Aug 2026, 09:45 AM', 'done' => true, 'icon' => 'fa-solid fa-users'],
                    ['title' => 'Scheduled', 'time' => '15 Aug 2026, 10:00 AM', 'done' => true, 'icon' => 'fa-regular fa-calendar'],
                    ['title' => 'Delivered', 'time' => '16 Aug 2026, 04:00 PM', 'done' => true, 'icon' => 'fa-solid fa-check'],
                ],
                'created_by'          => $adminId,
                'created_at'          => Carbon::parse('2026-08-15 09:30:00'),
                'updated_at'          => Carbon::parse('2026-08-16 16:00:00'),
            ],
            [
                'campaign_id'         => 'NTF-2026-0122',
                'name'                => 'Weekend Photo Contest Announcement',
                'title'               => 'Join the Weekend Geotag Photo Contest',
                'message'             => 'Submit your best geotagged landscape photos this weekend to win exclusive camera presets.',
                'action'              => 'Open App',
                'audience_type'       => 'segment',
                'audience_label'      => 'All High Activity Users • 3,450',
                'segment_id'          => $segmentId,
                'target_device_ids'   => null,
                'android_count'       => 2800,
                'ios_count'           => 650,
                'total_audience'      => 3450,
                'delivered_count'     => 3390,
                'open_count'          => 1620,
                'open_rate'           => 47.80,
                'status'              => 'sent',
                'scheduled_at'        => Carbon::parse('2026-08-14 11:00:00'),
                'sent_at'             => Carbon::parse('2026-08-14 11:00:00'),
                'time_zone'           => 'Asia/Kolkata',
                'quiet_hours_enabled' => true,
                'expiry_hours'        => 48,
                'timeline_steps'      => [
                    ['title' => 'Draft Created', 'time' => '13 Aug 2026, 10:00 AM', 'done' => true, 'icon' => 'fa-regular fa-file-lines'],
                    ['title' => 'Delivered', 'time' => '14 Aug 2026, 11:00 AM', 'done' => true, 'icon' => 'fa-solid fa-check'],
                ],
                'created_by'          => $adminId,
                'created_at'          => Carbon::parse('2026-08-13 10:00:00'),
                'updated_at'          => Carbon::parse('2026-08-14 11:00:00'),
            ],
            [
                'campaign_id'         => 'NTF-2026-0121',
                'name'                => 'Location Calibration Guide',
                'title'               => 'Calibrate GPS for Pinpoint Accuracy',
                'message'             => 'Learn how to improve GPS accuracy in low-signal areas with our step-by-step tutorial.',
                'action'              => 'Open URL',
                'audience_type'       => 'all',
                'audience_label'      => 'All Eligible Installations • 7,054',
                'segment_id'          => null,
                'target_device_ids'   => null,
                'android_count'       => 6400,
                'ios_count'           => 654,
                'total_audience'      => 7054,
                'delivered_count'     => 6920,
                'open_count'          => 2850,
                'open_rate'           => 41.20,
                'status'              => 'sent',
                'scheduled_at'        => Carbon::parse('2026-08-12 15:30:00'),
                'sent_at'             => Carbon::parse('2026-08-12 15:30:00'),
                'time_zone'           => 'Asia/Kolkata',
                'quiet_hours_enabled' => true,
                'expiry_hours'        => 24,
                'timeline_steps'      => [
                    ['title' => 'Delivered', 'time' => '12 Aug 2026, 03:30 PM', 'done' => true, 'icon' => 'fa-solid fa-check'],
                ],
                'created_by'          => $adminId,
                'created_at'          => Carbon::parse('2026-08-11 14:00:00'),
                'updated_at'          => Carbon::parse('2026-08-12 15:30:00'),
            ],
            [
                'campaign_id'         => 'NTF-2026-0120',
                'name'                => 'Coimbatore Users Meetup',
                'title'               => 'Special Preset Pack for Coimbatore',
                'message'             => 'Unlock exclusive South India geotag watermark badges in your camera app.',
                'action'              => 'Open App',
                'audience_type'       => 'segment',
                'audience_label'      => 'Location: Coimbatore • 540',
                'segment_id'          => $segmentId,
                'target_device_ids'   => null,
                'android_count'       => 490,
                'ios_count'           => 50,
                'total_audience'      => 540,
                'delivered_count'     => 525,
                'open_count'          => 298,
                'open_rate'           => 56.70,
                'status'              => 'sent',
                'scheduled_at'        => Carbon::parse('2026-08-10 18:00:00'),
                'sent_at'             => Carbon::parse('2026-08-10 18:00:00'),
                'time_zone'           => 'Asia/Kolkata',
                'quiet_hours_enabled' => true,
                'expiry_hours'        => 24,
                'timeline_steps'      => [
                    ['title' => 'Delivered', 'time' => '10 Aug 2026, 06:00 PM', 'done' => true, 'icon' => 'fa-solid fa-check'],
                ],
                'created_by'          => $adminId,
                'created_at'          => Carbon::parse('2026-08-09 16:00:00'),
                'updated_at'          => Carbon::parse('2026-08-10 18:00:00'),
            ],
            [
                'campaign_id'         => 'NTF-2026-0119',
                'name'                => 'Monthly Security & Performance Patch',
                'title'               => 'Security & Performance Update Available',
                'message'             => 'Update to version 2.4.1 for faster photo processing and battery optimizations.',
                'action'              => 'Deep Link',
                'audience_type'       => 'all',
                'audience_label'      => 'All Eligible Installations • 7,054',
                'segment_id'          => null,
                'target_device_ids'   => null,
                'android_count'       => 6400,
                'ios_count'           => 654,
                'total_audience'      => 7054,
                'delivered_count'     => 0,
                'open_count'          => 0,
                'open_rate'           => null,
                'status'              => 'scheduled',
                'scheduled_at'        => Carbon::parse('2026-08-28 09:00:00'),
                'sent_at'             => null,
                'time_zone'           => 'Asia/Kolkata',
                'quiet_hours_enabled' => true,
                'expiry_hours'        => 72,
                'timeline_steps'      => [
                    ['title' => 'Draft Created', 'time' => '25 Aug 2026, 08:30 AM', 'done' => true, 'icon' => 'fa-regular fa-file-lines'],
                    ['title' => 'Scheduled for Delivery', 'time' => '28 Aug 2026, 09:00 AM', 'done' => false, 'icon' => 'fa-regular fa-calendar'],
                ],
                'created_by'          => $adminId,
                'created_at'          => Carbon::parse('2026-08-25 08:30:00'),
                'updated_at'          => Carbon::parse('2026-08-25 08:30:00'),
            ],
            [
                'campaign_id'         => 'NTF-2026-0118',
                'name'                => 'Beta Feedback Survey',
                'title'               => 'Help Us Improve GPS Camera',
                'message'             => 'Take a 1-minute survey and get 3 free premium template designs.',
                'action'              => 'Open URL',
                'audience_type'       => 'segment',
                'audience_label'      => 'Tamil Nadu Android Beta • 1,200',
                'segment_id'          => $segmentId,
                'target_device_ids'   => null,
                'android_count'       => 1200,
                'ios_count'           => 0,
                'total_audience'      => 1200,
                'delivered_count'     => 0,
                'open_count'          => 0,
                'open_rate'           => null,
                'status'              => 'draft',
                'scheduled_at'        => null,
                'sent_at'             => null,
                'time_zone'           => 'Asia/Kolkata',
                'quiet_hours_enabled' => true,
                'expiry_hours'        => 24,
                'timeline_steps'      => [
                    ['title' => 'Draft Created', 'time' => '22 Aug 2026, 02:00 PM', 'done' => true, 'icon' => 'fa-regular fa-file-lines'],
                ],
                'created_by'          => $adminId,
                'created_at'          => Carbon::parse('2026-08-22 14:00:00'),
                'updated_at'          => Carbon::parse('2026-08-22 14:00:00'),
            ],
            [
                'campaign_id'         => 'NTF-2026-0117',
                'name'                => 'Camera Flash Mode Notice',
                'title'               => 'Night Mode Flash Calibration',
                'message'             => 'Night mode camera stamps now automatically enhance exposure settings.',
                'action'              => 'Open App',
                'audience_type'       => 'all',
                'audience_label'      => 'All Eligible Installations • 7,054',
                'segment_id'          => null,
                'target_device_ids'   => null,
                'android_count'       => 6400,
                'ios_count'           => 654,
                'total_audience'      => 7054,
                'delivered_count'     => 6810,
                'open_count'          => 3120,
                'open_rate'           => 45.80,
                'status'              => 'sent',
                'scheduled_at'        => Carbon::parse('2026-08-08 19:30:00'),
                'sent_at'             => Carbon::parse('2026-08-08 19:30:00'),
                'time_zone'           => 'Asia/Kolkata',
                'quiet_hours_enabled' => true,
                'expiry_hours'        => 24,
                'timeline_steps'      => [
                    ['title' => 'Delivered', 'time' => '08 Aug 2026, 07:30 PM', 'done' => true, 'icon' => 'fa-solid fa-check'],
                ],
                'created_by'          => $adminId,
                'created_at'          => Carbon::parse('2026-08-07 15:00:00'),
                'updated_at'          => Carbon::parse('2026-08-08 19:30:00'),
            ],
            [
                'campaign_id'         => 'NTF-2026-0116',
                'name'                => 'iOS Notification Permission Renewal',
                'title'               => 'Keep Receiving Live Location Alerts',
                'message'             => 'Enable push alerts in iOS Settings to receive instant map coordinate sync.',
                'action'              => 'Open App',
                'audience_type'       => 'segment',
                'audience_label'      => 'Individual Devices • 12',
                'segment_id'          => null,
                'target_device_ids'   => null,
                'android_count'       => 0,
                'ios_count'           => 12,
                'total_audience'      => 12,
                'delivered_count'     => 0,
                'open_count'          => 0,
                'open_rate'           => 0.00,
                'status'              => 'failed',
                'scheduled_at'        => Carbon::parse('2026-08-05 10:00:00'),
                'sent_at'             => Carbon::parse('2026-08-05 10:00:00'),
                'time_zone'           => 'Asia/Kolkata',
                'quiet_hours_enabled' => true,
                'expiry_hours'        => 24,
                'timeline_steps'      => [
                    ['title' => 'Failed Delivery', 'time' => '05 Aug 2026, 10:00 AM', 'done' => false, 'icon' => 'fa-solid fa-triangle-exclamation'],
                ],
                'created_by'          => $adminId,
                'created_at'          => Carbon::parse('2026-08-04 11:00:00'),
                'updated_at'          => Carbon::parse('2026-08-05 10:00:00'),
            ],
        ];

        foreach ($campaigns as $data) {
            NotificationCampaign::updateOrCreate(
                ['campaign_id' => $data['campaign_id']],
                $data
            );
        }
    }
}
